---
apiVersion: kubeit.komailo.github.io/v1alpha1
kind: NamedValues
metadata:
  name: production
spec:
  values:
    - type: mapping
      data:
        controller.image.tag: staging$dockerImageTag
        controller.image.repository: envValue$dockerImageRepository
    - type: raw
      data:
        controller:
          image:
            repository: staging.io/kubernetes-ingress-controller/nginx-ingress-controller
