# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: kubeit

before:
  hooks:
    - go mod tidy

builds:
  - id: kubeit-cli
    main: ./cmd/main.go
    binary: kubeit-{{ .Os }}-{{ .Arch }}
    ldflags:
      - "-X github.com/komailo/kubeit/common.version={{ .Version }}"
      - "-X github.com/komailo/kubeit/common.buildDate={{ .Date }}"
      - "-X github.com/komailo/kubeit/common.gitCommit={{ .FullCommit }}"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: kubeit-archive
    builds:
      - kubeit-cli
    name_template: |-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}
    formats:
      - binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

release:
  prerelease: auto
  draft: false
