# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: kubeit

before:
  hooks:
    - go mod tidy

builds:
  - id: kubeit-cli
    main: ./main.go
    binary: kubeit-{{ .Os }}-{{ .Arch }}
    ldflags:
      - "-X github.com/komailo/kubeit/internal/version.buildDate={{ .Date }}"
      - "-X github.com/komailo/kubeit/internal/version.gitCommit={{ .FullCommit }}"
      - "-X github.com/komailo/kubeit/internal/version.gitSummary={{ .Summary }}"
      - "-X github.com/komailo/kubeit/internal/version.gitTreeState={{ .GitTreeState }}"
      - "-X github.com/komailo/kubeit/internal/version.version={{ .Version }}"
      #- "-s -w"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: kubeit-archive
    builds:
      - kubeit-cli
    name_template: |-
      {{ .ProjectName }}-{{ .Os }}-{{ .Arch }}
    format: binary

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

release:
  prerelease: auto
  draft: false
