version: "3"

tasks:
  setup:
    desc: "Setup the local environment project development"
    cmds:
      - go mod download
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install github.com/goreleaser/goreleaser@latest
      - go install github.com/segmentio/golines@latest
      - go install mvdan.cc/gofumpt@latest

  build:
    desc: "Build the Go project"
    deps:
      - go-mod-tidy
    cmds:
      - go build -o build/reflow .

  fmt:
    desc: "Format Go code"
    cmds:
      - "$(go env GOPATH)/bin/golines --write-output ."
      - "$(go env GOPATH)/bin/golangci-lint run --fix"

  run:
    desc: "Run the Main CLI with arguments"
    cmds:
      - build/reflow {{.CLI_ARGS}}
    deps:
      - build

  lint:
    desc: "Run golangci-lint"
    cmds:
      - ~/go/bin/golangci-lint run

  generate:
    deps:
      - generate-schema
      - generate-cli-docs

  generate-schema:
    desc: Generate the schema for apis
    cmds:
      - build/reflow generate-schema
    deps:
      - build

  generate-cli-docs:
    desc: Generate the CLI documentation for tool
    cmds:
      - build/reflow generate --output-dir ./docs cli-docs
    deps:
      - build

  ### Test operations
  test:
    desc: "Run tests"
    deps:
      - go-tests
    cmds:
      - build/reflow generate manifest file://$(pwd)/examples/reflow-helm/ --kube-version 1.21.0
      - build/reflow generate manifest ./examples/reflow-helm-oci/ --kube-version 1.21.0
      - build/reflow generate manifest foo:latest --kube-version 1.21.0
      - build/reflow generate manifest docker://foo:latest --kube-version 1.21.0

  go-tests:
    desc: "Run Go tests"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - go tool cover -func=coverage.out
  ### End test operations

  int-test:
    desc: "Run integration test"
    cmds:
      - docker build $(task run -- generate docker-labels ./examples/reflow-helm) -t foo ./examples
      - task run -- generate manifest file://$(pwd)/examples/reflow-helm/
      - task run -- generate manifest ./examples/reflow-helm-oci/
      - task run -- generate manifest foo:latest
      - task run -- generate manifest docker://foo:latest

  ## Go related operations
  go-mod-tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  go-mod-update:
    desc: Update go modules
    deps:
      - go-mod-tidy
    cmds:
      - go get -u ./...
  ## End Go related operations

  go-releaser-local:
    desc: Run Go releaser locally to produce artifacts
    cmds:
      - ~/go/bin/goreleaser --snapshot --skip=publish --clean
