version: "3"

tasks:
  build:
    desc: "Build the Go project"
    cmds:
      - go build -o build/kubeit ./cmd/main.go

  fmt:
    desc: "Format Go code"
    cmds:
      - go fmt

  run:
    desc: "Run the KubeIt CLI with arguments"
    cmds:
      - build/kubeit {{.CLI_ARGS}}
    deps:
      - build

  lint:
    desc: "Run golangci-lint"
    cmds:
      - ~/go/bin/golangci-lint run

  generate:
    deps:
      - generate-schema
      - generate-cli-docs

  generate-schema:
    desc: Generate the schema for Kubeit configuration
    cmds:
      - build/kubeit generate-schema
    deps:
      - build

  generate-cli-docs:
    desc: Generate the CLI documentation for Kubeit
    cmds:
      - build/kubeit generate --output-dir ./docs cli-docs
    deps:
      - build

  test:
    desc: "Run tests"
    cmds:
      - go test -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out -o coverage.html
      - go tool cover -func=coverage.out
