---
apiVersion: kubeit.komailo.github.io/v1alpha1
kind: HelmApplication
metadata:
  name: app
spec:
  chart:
    repository: https://kubernetes.github.io/ingress-nginx/
    name: ingress-nginx
    version: ">=4.11.2"
    releaseName: my-nginx
  values:
    - type: mapping
      data:
        controller.image.tag: $dockerImageTag
        controller.image.repository: $dockerImageRepository
        kubeitVersion: $kubeitVersion
    - type: raw
      data:
        controller:
          image:
            tag: 0.46.0
            repository: quay.io/kubernetes-ingress-controller/nginx-ingress-controller
